---
- hosts: windows

  tasks:
    - name: get-freeDiskSpace
      win_shell: get-volume | select @{n="Size Remaining [GB]";e={$_.sizeremaining/1GB}}
      register: script_return
    - debug:
       msg: "{{ script_return.stdout }}"
