---
- hosts: Linux
  become: true
  roles:
    - Linux


- hosts: windows
  roles: 
    - windows


- hosts: all
  roles:
    - base


- hosts: web_servers
  roles:
    - web_servers


- hosts: file_servers
  roles:
    - file_servers  
