---

- hosts: Linux
  become: true
  pre_tasks:
    
    - name: install updates (CentOS)
      tags: always
      yum:  update_cache=yes 
      changed_when: false
      when: ansible_distribution|lower is match(".*centos.*")
    
    - name: install updates (Ubuntu)
      become: true
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution|lower is match(".*ubuntu.*")

- hosts: Linux
  become: true
  tasks:

    - name: add ssh key to the test user
      tags: always
      authorized_key: 
        user: test
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEEWdu+xwH6sho8MIIMeMFKmLD197114XkjBKk/lmEg Ansible_Key"


- hosts: web_servers
  tasks:
    
    - name: install apache (CentOS)
      tags: centos, httpd, apache
      become: true
      yum:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_distribution|lower is match(".*centos.*")
    
    - name: change e-mail address for admin
      become: true
      tags: centos, httpd, apache
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution|lower == "centos"
      register: httpd

    - name: restart httpd (CentoOS)
      become: true
      tags: centos, httpd, apache
      service: 
        name: httpd
        state: restarted
      when: httpd.changed


    - name: copy default html file for site
      become: true
      tags: centos, httpd, apache
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution|lower == "centos"
    
    - name: start httpd service
      become: true
      tags: centos, httpd, apache
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution|lower == "centos"


- hosts: file_servers
  tasks:

    - name: install FS-role
      tags: windowsFS
      win_feature:
        name: 'FS-FileServer'
      register: output2
      when: ansible_distribution|lower is match(".*windows.*")

