ansible_connection: psrp
ansible_psrp_auth: credssp
ansible_psrp_operation_timeout: 7
ansible_psrp_connection_timeout: 8
ansible_psrp_read_timeout: 32
ansible_become_method: runas
ansible_user: ansible
ansible_password: ansible
ansible_port: 5986
ansible_psrp_cert_validation: ignore
